baseURL = "https://urmelweb.netlify.app/"
languageCode = "en-us"
title = "Urmel Kinderladen e.V."
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Elterninitiative in Berlin Neukölln"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Über"
    weight = 2

[[menu.main]]
    url = "/concept/"
    name = "Konzept"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Plätze"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

